# THE SOVIET UNION (Population 218 million)

## General

Throughout 1960 and the first half of 1961 the Soviet military policy followed the same course as that pursued by the United States in the mid-1950s and by Britain after 1957: an attempt was made to absorb the cost of technological development and new weapons by placing increased emphasis on nuclear fire power and reducing the amount of mobilized manpower. It was clear that the Soviet government had, at the end of 1959, reached a considered decision that their progress in missile technology, coupled with the demands of the economy, especially agriculture, for more men, justified such a policy. However, during July 1961, the Soviet government announced, in response to its own estimate of a darkening inter- national horizon, a revision of this emphasis on the deterrent effect of nuclear missiles, and has been anxious since then to make clear that it is building up the strength of virtually all its forces except surface ships. Under the law of January 15, 1960, the Soviet forces were to be reduced from 3,623,000 men to 2,423,000 men by the end of 1961, a reduction of 1,200,000 men over two years, but its suspension was announced on July 8, 1961. No official Soviet figures of the current strength of the forces has been published but it is not likely that more than 600,000 men were demobilized, principally in the ground forces. Thus the total strength of the forces in mid-1961 was about 3,000,000 men. In addition, it was announced on August 29, 1961, that the demobilization of certain categories of other ranks, whose period of military service was completed, had been suspended until the signature of a German peace treaty. When men called up in 1961 have completed their training and been absorbed into units at the end of the year, the effect of this decree (unless it is rescinded) will be to increase the size of the Soviet forces by up to 800,000 men, giving a total strength of perhaps 3,800,000 men - some five per cent larger than at the end of 1959.

The Soviet military budget for 1961 (calendar year) was set at 9,255 million roubles (\$10,180 million) but it was announced on July 8, 1961, that it would be increased by one-third, i.e. 3,114 million roubles (\$3,415 million) to 12,339 million roubles (\$13,573 million). In real terms, the total size of the augmented Soviet budget is estimated to be of the order of between \$20,000 and \$25,000 million. It is not likely that all this one-third increase can be spent during 1961, and only part of it will be needed to meet the increased bill for man- power; this suggests that it is also intended to accelerate weapons development and production.

## Air and Missile Power

Soviet policy statements continue to place marked emphasis on the development of long range missiles as a deterrent to aggression and a support to diplomacy. It is considered possible that the Soviet Union could, if the programme had rated a high enough priority, have by now built up a force of 200 ICBMs, the original three-stage liquid- fuelled missile which has been under development since the mid-fifties. The reasons that make it doubtful if they have actually created an operational force of this size are:

(a) the difficulties of building bases for so large a missile and their strategic vulnerability:
(b) the fact that they now have a smaller second generation ICBM under active development which is likely to be easier to conceal:
(c) the demands of the Soviet space and other programmes upon scientific man- power:

Consequently the present figure of operational ICBMs is more likely to be in the neighbourhood of 50 than 200.

Unlike the United States Soviet policy places considerable emphasis on concealment of bases. Apart from the two main missile test centres near the Caspian Sea, it can be assumed only that the location of ICBM sites are influenced by the rail communications network.

As far as MRBMs are concerned, the figure of 200 has been quoted in the West, and in view of Soviet concentration on MRBMs this estimate seems reasonable. Soviet state- ments allege that they exist in considerable quantities, and since there are not the same indications of a need to decelerate their build-up in order to make room for a more advanced type as with ICBMs, this is very probably the case. From their ranges and from published Soviet statements, it is reasonably clear that Soviet policy is to site them near the western, southern and eastern borders of the Soviet Union, on the Pacific coast and in Siberia, so that they cover the main bases of Western medium range air and missile power from Britain to Okinawa and Japan.

The strategic missile forces are organized as an autonomous arm of the service, under the command of Marshal Kiril Moskalenko. In July 1961 Marshal Malinovsky, the Soviet Defence Minister, spoke of the reorganiza- tion of the Soviet forces to create tactical missile units capable of operating independently.

In spite of their concentration on rockets and ballistic missiles, the Russians have not neglected their Air Force, which comprises some 15,000 operational aircraft, organized into five major components, namely:

(1) the long-range strategic bomber force;
(2) the tactical, or front line, force which includes fighters and tactical bombers;
(3) the fighter interceptor force;
(4) the land-based fleet air arm;
(5) the air transport force.

The heavy bomber force has been kept at a considerably lower strength than that of the US Strategic Air Command, though the general lines of development, including stand-off bombs and missiles, are similar. On the other hand the Soviet Union has built up a very strong force of medium bombers suitable for use all over the Eurasian theatre and its coasts, and an efficient light bomber force. It seems probable that, partly as a result of service and industrial pressure, higher priority is being given to aircraft development than in the late fifties. The following gives some indication of Soviet strength in this field.

### (i) Strategic Striking Power

#### Missiles

(a) The principal operational ICBM is propelled by a three-stage liquid fuel engine and has an operational range of up to 8,000 miles. A second generation ICBM is now being developed. It is propelled by a storable liquid fuel and will probably be smaller and more accurate than its predecessor, but still more bulky than the US Minuteman.

(b) There are two operational IRBMs. One has a range of about 1,800 miles and is propelled by a two-stage liquid fuel engine: the other has a range of about 1,000 miles, is also liquid fuelled, and can carry a 1,800 lb atomic warhead.

#### Long-range and Medium Bombers

The Strategic Bomber Force consists mainly of the following aircraft:

(a) 70 turbo-prop Bears[^1] (TU 20); range 7,000 miles, bomb-load 20 tons, maximum speed 550 miles per hour, now able to carry two short range air to ground missiles similar to US Hound Dog. 
120 4-jet Bisons; range 6,050 miles, bomb- load 10 tons, maximum speed 600 miles per hour, operational ceiling 50,000.

(b) 1,000 twin-jet medium bomber Badgers (TU 16); range 3,500 miles, bomb-load 4-5 tons, speed 587 miles per hour, operational ceiling 40,000 feet. Delta-wing 4-jet Bounder (similar to but somewhat larger than the US B58), speed supersonic (probably Mach 2), range 1,650 miles; said to be capable of using grass runways; prototype displayed in 1961. New types shown at Tushino Air Show in 1961 included nine of a medium bomber, Blinder, somewhat similar to the US B58 and probably being developed for use with a longer range air to ground missile comparable to Skybolt, and capable of air refuelling.

A small proportion of this force is based on the Kola peninsula and in Siberia, while the rest is based in western and south-west Russia. Bisons and Badgers have also been adapted as tankers for in-flight refuelling.

[^1]: It should be made clear that this menagerie of names for Soviet aircraft is of NATO, not Soviet, origin.

### (ii) Tactical Air Power

It is clear that the tactical bomber forces are going through a much sharper period of transition than the heavy bomber forces, with older aircraft such as the turbo-jet Beagle and possibly the twin-jet Blowlamp and Backfin, being replaced. The earlier estimate of 4,000 operational aircraft is therefore now too high. The principal tactical bombers under development had been (a) the supersonic twin-jet Blowlamp, comparable to the RAF Canberra, with a high altitude range of 745 miles and a speed of 750 miles per hour (this was not displayed at the 1961 Air Show), and the twin-jet Backfin with a speed of 800 miles per hour.

Effort now seems to be concentrated on a new twin-jet ground attack aircraft with transonic capabilities and a wide radius of action which, like the new all-weather fighter, seems to be an improved version of Flash- is provisionally known as Flashlight B.

### (iii) Air Defence

The number of ground-to-air guided mis- siles and high-performance fighters for air defence has been steadily increased and an extensive early warning system is in operation. The following are details of air defence equipment:

#### Ground-to-Air Guided Missiles

A radar-directed rocket, which is already in service and is considered to be highly effective. It is propelled by one main and one auxiliary solid fuel engine. Its slant range is 20 miles, and it rises to a height of 12 miles (60,000 feet).

There may also be a high-altitude guided missile with radio guidance, and there is an anti-aircraft missile which has a range of 18 miles and speed over 1,500 miles per hour.

#### Fighter Planes

It is estimated that there are about 10,000 fighter aircraft of all kinds, and that intensive development is in hand to produce types with higher ceilings and improved air-to-air weapons.

(a) The standard all-weather interceptor of recent years, the subsonic Yak 25 Flash- light, is now obsolescent, although two improved versions, one of them redesigned as a light bomber, are still in service. How- ever a new all-weather delta-winged inter- ceptor provisionally called Flashlight C, was displayed in July 1961.

'Table 1

In April 1961 the Soviet Union claimed a world height record of 110,000 feet for a delta-winged "E 66" which was almost cer- tainly Fishbed. (The official world record of 103,000 feet is still held by a US F102.)

## Land Power

No official figures of the Soviet Army have been published but with the partial arresting of demobilization and the retention of the 1961 conscripts its total size is estimated at up to 2,500,000 (an increase of 250,000 on 1960). As a result of this year's special measures it is organized in approximately 160 active line divisions (not all at full strength). An infantry division at war strength com- prises 12,000 men, an armoured division about 10,500 plus supporting artillery and anti-aircraft units. Most of the active divisions are armoured or mechanized.

In East Germany there are 10 tank divisions each with 400 tanks, and 10 mech- anized divisions, each with 250 tanks. All are operational and comprise a total of over 6,000 tanks. In Hungary and Poland there are 6 divisions. It is estimated that the Soviet Union has a total mobilization potential of 7 million men including all types of reservists.

The airborne forces of the Soviet Union total approximately 100,000 men formed in 9 divisions. The airborne troops are sup- ported by the transport fleet, which would enable about two divisions to be air-dropped or air-landed in any single operation.

In recent years, the Soviet Army has undergone a major reorganization to meet conditions of atomic warfare. Many of its units have been completely re-equipped twice over in the last ten years and, thanks to the introduction of modern weapons, its fire power has been vastly increased. Though the Soviet Union has not shown as much interest as the United States in the development of very low yield nuclear weapons for tactical purposes, nuclear warheads are available for many of the missiles mentioned below. Mr Khrushchev has hinted broadly that the Soviet forces in East Germany have tactical nuclear weapons.

Soviet Army equipment includes:

### (i) Tanks

The total tank strength of the Soviet Army is estimated at 20,000 front-line tanks and 15,000 second-line tanks. The new tanks which have been introduced into the Soviet armoured divisions are the T.54 medium tank, fitted with a 100 mm. gun, and the 54-ton heavy tank T.10, which mounts a 122 mm. gun.

### (ii) Artillery

The Soviet Army is very strong in artillery. Artillery weapons include the atomic 203 mm. cannon mounted on mobile platforms, with a range of 15 miles; and 240 mm. heavy mortars or unguided rockets with a range of 20 miles, together with many other types of mortars. Though many artillery tasks are to be performed by missiles, the Soviet Army still considers that many im- portant functions remain for rifled artillery.

### (iii) Missiles

An improved version of the German V2 ballistic rocket is the standard equipment of

the tactical units. Propelled by one liquid fuel engine, it has a range of 450 miles. It can be fired from a mobile ramp, is radio guided and can carry a nuclear warhead. There is a solid fuel ballistic missile with a range of 50 miles, which may be obsolete, and two smaller versions, carried on self- propelled launchers with ranges from 10 to 15 miles (equivalent to US Honest John). There is also a truck-launched missile with a range of 50 miles, which fires an HE warhead. A range of anti-tank missiles has also been developed.

## Sea Power

The Soviet Navy, which is manned by about 500,000 officers and men, has increased from a total tonnage in 1940 of 600,000 to 1,600,000 tons today, which makes it the most powerful fleet in the world after the United States (4 million tons).

### (i) Submarines

The main strength of the Soviet Navy lies in the submarine fleet.

The submarine force is generally estimated to comprise at least 430 units, of which 85 are based in the Baltic, 65 in the Black Sea, 140 in the Arctic, 120 in the Far East. Eight formerly based in the Mediterranean, on the Albanian ports of Durazzo and Valona, have been withdrawn. It is expected that in the foreseeable future, 75 per cent of the submarine fleet will con- sist of ocean-going craft of which a propor- tion will be atomic powered. At the moment, Russia has 6 atomic powered submarines in various stages of construction of which one or two may be at sea. The following are details of the conven- tionally powered submarine fleet: The F class is about 300 feet long, has a displacement of 2,000 tons, and a large radius of action. At least 10 of these are in service. The G class is 310 feet long and has a submerged displacement of 2,700 tons. It has a very large conning tower for the vertical launching of an unknown number of missiles which are fired when on the surface.

The W class is 245 feet long with a 1,050 tons displacement. It has a speed of 16 knots on the surface and 13 knots submerged, and a radius of action of 10,000 miles. There are about 130 of these in service. The Z class is 290 feet long with a sub- merged displacement of 2,600 tons. It is capable of 20 knots on the surface and 13 knots submerged, with a radius in excess of 20,000 miles. There are at least 20 of these in service. A small number have been con- verted to fire missiles, probably in a manner similar to the G class. They are stationed principally in the Baltic and the Far East. The K and Q type, which were built between 1945 and 1955, are medium range vessels; their radius of action is about 7,000 miles and their displacement varies from 1,400 to 680 tons.

### (ii) Surface Ships

The surface ships of the Soviet Navy consist of :

(There are also a number of disguised trawlers used for radar and recon- naissance purposes.)

These are distributed more or less equally between the Baltic, Black Sea, Northern and Pacific fleets.

'Table 1

The cruisers are of three different types:

(a) 17 Sverdlov, launched between 1951 and 1957, displacement 15,500 tons, speed 34 knots, armament 12 152 mm. guns and 32 anti-aircraft guns;

(b) 5 Chapayev class, completed between 1948 and 1951, of 11,500 tons displacement, with the same speed and armament as the Sverdlov;

(c) 6 Kirov and Gorki class, launched between 1936 and 1945, displacement 8,500 tons, speed 30 knots, armament 9 180 mm. guns and 20 anti-aircraft guns.

Four or more almost completed Sverdlov cruisers appear to have been scrapped.

The greater part of the destroyers are modern, having been constructed since 1950, and some are fitted with guided missiles.

Their displacement varies from 1,000 to 2,700 tons, and their speed from 28 to 38 knots.

### (iii) Fleet Air Arm

There are no aircraft carriers in the Soviet Navy, but there is a land-based Fleet Air Arm which now appears to be getting a lower priority than formerly. It consists mainly of:

(a) the torpedo-carrying IL 28 Beagle and TU 14 Bosun with ranges of 1,500-1,800 miles;

(b) the TU 16 Badger - range of 3,500 miles.

A new twin-jet swept-wing flying boat and an anti-submarine turbine helicopter with a short range missile were displayed in 1961.

### (iv) Sea-to-ground Missiles

There are believed to be two types. One has a range of about 100 miles and the other of about 400 miles. The 100 miles range missile is believed to be solid fuelled and can be fired either from a surface craft or a surfaced submarine. The 400-mile missile is designed for submarines but can only be fired from the surface.

Soviet claims to have an equivalent of the Polaris missile, which can be fired from a submerged submarine, are misleading.

