# CHINA

## The Army

(i) The Army consists of 2,216,000 men, organized in: approximately 115 divisions of infantry; 2 or 3 armoured divisions; 1 or 2 airborne divisions; supporting troops; and cavalry for desert areas. There are 125,000,000 men of military age in 1961. About 700,000 are called up each year, and serve three years in the Army.

(ii) The armed forces are organized by the Ministry of Defence, advised by a National Defence Council whose Chairman is the Chairman of the People's Republic: control is exercised through 13 Military Regions. The Land Army consists of about 30-35 armies. These are of 3 divisions each, i.e. an Army is equivalent to a Western Army Corps. In peacetime there is no operational headquarters higher than the Army; but in wartime Armies are grouped in Field Armies. The strength of an active Army could be between 50,000-60,000.

(iii) No reliable figures are available for the size of the Militia, but the declared intention is to embody every third person in the population. It is static, sketchily armed, and organized as much for forced labour as defence. The Public Security forces, including the armed police, consist of about 200,000 men.

## The Air Force

This has a total strength of 3,000 aircraft, including 400 naval aircraft. China is now building jet fighters and trainers, but the backbone of the force consists of Soviet MIG 15s, 17s and probably 19s, IL 28 light bombers and helicopters. Training is inhibited by shortage of aviation spirit.

## The Navy

China has no operational ships heavier than destroyers, of which there are 4. There are 26 submarines (a small increase on 1960), of which half are Soviet W class medium range craft; frigates; MTBs; gun- boats and patrol craft. The Navy is not an offensive force and is ineffective except for inshore defence.
