# STRATEGIC FORCES

These are under national command and comprise the United States Strategic Air Command, RAF Bomber Command, the United States First and Seventh Fleets and the United States nuclear powered sub- marines, equipped with the Polaris missiles. In addition, IRBM bases in Europe are in operation or under construction. Exceptions to the nationally controlled strategic forces are the NATO controlled Striking Fleet Atlantic, which is also nationally designated the US Second Fleet and the NATO Carrier Striking Force, South, which is nationally designated the US Sixth Fleet, operating in the Mediterranean. An essential component of the strategic forces of the West is its air and missile warning systems.

## (1) United States Air and Missile Bases

The chief concern of United States defence in the eventuality of a general war will be a surprise attack by nuclear-armed ICBMs. For this, it is developing forces which can survive and respond to a first attack. Strategic Air Command is divided into

(a) the Fifth Air Force with Headquarters in California, and the Second and Eighth Air Force with Headquarters in Louisiana and Massachusetts.

(b) the First Missile Division with Head- quarters in California.

(c) the 16th Air Force in Spain, the 7th Air Division in the UK, and the 3rd Air Division based on Guam. Each of these overseas units operates several advance bases.

### Strategic Aircraft

The SAC has over 1,500 bombers capable of delivering nuclear bombs. Of these, some 1,000 are B.47s, and 600 are long-range B.52s based in the United States. Both types of aircraft use in-flight refuelling to extend their range. The B.58, of which there are between thirty and forty now in service, will partially replace the B.47.

One-third of these forces is now kept continuously on 'ground alert', which will enable them to leave their bases within 15 minutes of receiving warning of attack. The proportion is to be increased to one-half by the middle of 1962.

### Missiles 

The First Missile Division operates the Atlas and Titan ICBMs. The present long-term programme comprises 25 Atlas and Titan squadrons, including 6 Atlas squadrons with 12 missiles permanently on launchers. By early in 1962 three main bases of the present 'soft' Vandenberg and Warren types will have been completed. By then there will also be one 'hard' Titan base (at Denver, Colorado) and two more 'semi-hard' Atlas bases. This will mean that 54 Atlas and nine Titans are operational.

The Snark guided missile is to be withdrawn by the end of 1961.

The Minuteman, a solid propellant ICBM, capable of being mounted on a mobile base (though the first six squadrons are to be based on fixed sites), will not be operational until late in 1962.

## (2) RAF Bomber Command

RAF Bomber Command is equipped with about 180 Vulcan, Valiant and Victor bombers, capable of carrying free falling nuclear or conventional bombs. They are able to refuel in flight from Valiant jet tankers. (It is now doubtful if the guided stand-off bomb Blue Steel, with a range of 400 miles, will be available in 1962.)

## (3) European Missile Bases

There are sixty Thor IRBMs based in the United Kingdom. Work on the site for 30 Jupiter IRBMs in Italy is scheduled to be completed by the end of 1961. There is no evidence that work on the site for 15 more Jupiters in Turkey is proceeding.

## (4) Seapower

### Surface Ships

(a) The United States 1st, 2nd, 6th and 7th Fleets each comprise about fifty ships and have aircraft carriers as a nucleus. The US First Fleet is based on the west coast of the United States, ready to be deployed separately or to augment the US Seventh Fleet in the Far East on a national basis. The other western nations have six air- craft carriers in the Atlantic area, and Britain's will shortly have a nuclear strike capability.

(b) The United States nuclear powered submarine force, armed with the IRBM Polaris, is now operational. Six submarines, each equipped with 16 missiles, will be com- missioned by the end of 1961, and a further 3 by the end of 1962. The A.2, an improved version of the Polaris, with a range of 1,500 miles, is soon to be in production.

## (5) Warning Systems

(a) BMEWS. Two Ballistic Missile Early Warning System stations are in operation in Greenland and Alaska. The third station, at Fylingdales, Yorkshire, will be completed early in 1962. These will provide fifteen minutes' warning for that part of the SAC force which is to be kept on ground alert.

(b) MIDAS. The development of the Missile Defence Alarm System satellite is to be accelerated. This will provide thirty minutes' warning, which BMEWS would then serve to confirm. Fylingdales is also to have a reception system for MIDAS signals.

## (6) Strategic Reserves

United States: The Strategic Army Corps, which forms the main element of the United States strategic reserve, consists of two airborne divisions and one infantry division, totalling some 110,000 men. The infantry division is supported by elements armed with the Honest John field missile. There is a possibility that one of these divisions will be sent to join the 7th Army in Europe, in which case it would be replaced in the US by a National Guard division. The President has announced his intention of adding 3 divisions to the Continental Army Com- mand and assigning them to STRAC by the middle of 1962.

The total number of men in the US Continental Army Command is at present about 250,000.

United Kingdom: The elements of the Strategic Reserve which are assigned for reinforcement of the BAOR consist of the main part of the Parachute Brigade based in the UK, which will operate in association with some infantry battalions, and a division of two infantry brigades at present being built up in England.

France: There are now two divisions stationed in France and two in Algeria. These are considered as reinforcements for the Central Area of NATO in the event of hostilities.

Canada: Two brigade groups stationed in Canada are earmarked for the Supreme Commander in the event of hostilities.
