
# CENTRAL TREATY ORGANIZATION

The members of CENTO are Pakistan, Iran, Turkey, and the United Kingdom, with the United States as an associate member. The scope of the Treaty involves co-operation over a wider field than defensive preparation. CENTO does not have an international command structure as NATO does, nor are national forces allocated to it at present. Co-ordination is exercised by a Council of

military deputies including an American representative in Ankara. The main emphasis so far has been on the development of com- munications and air field to give flexibility to the forces available in the area. Strategic deterrent forces could be rapidly deployed in the area by the US 6th Fleet, from SAC bases in Turkey, and from British bases in Cyprus.

## NATIONAL FORCES

## IRAN

### General 

Population: 20,000,000

Two years military service

Total armed forces: 210,000

Defence budget: $147,587,000

### Army 

Total strength: 196,000

12 divisions

6 independent brigades

### Navy 

Total strength: 6,000

2 corvettes

3 coastal minesweepers

5 small ships

### Air Force 

Total strength: 8,000

Equipped with:

F.86 Sabrejets

F.84 Thunderjets

C.47 transports

## PAKISTAN

### General

Population: 94,000,000

Voluntary military service

Total armed forces: 182,700

Defence budget: $207,780,000

### Army 

Total strength: 160,000

Navy Total strength: 7,700

I cruiser

8 destroyers and frigates

II small ships

### Air Force 

Total strength: 15,000

F.86 fighter squadrons

Transport units

