
# SOUTH-EAST ASIA TREATY ORGANIZATION

The members of SEATO are Australia, France, New Zealand, Pakistan, the Philip- pine Republic, Thailand, the United King- dom and the United States. SEATO does not yet have a centralized command struc- ture and forces remain under national con- trol. SEATO co-operation is concerned not only with military defence against aggression, but also with the problem of subversion.

The main strategic forces are provided by the US Seventh Fleet (see strategic forces,

p\. 9) based on Manila, units of Strategic Air Command based on Okinawa and Guam and the British Far Eastern Fleet based on Singapore.. The Commonwealth Strategic Reserve in Malaya includes British, Austra- lian and New Zealand battalions and sup- porting units, and Australian and New Zealand naval and tactical air units, but the Malay Federation has recently made it clear that bases in Malaya would not be available for SEATO operations.

## NATIONAL FORCES

## AUSTRALIA

### General 

Population: 10,500,000

Voluntary military service

Total armed forces: 48,500

Defence budget: $445,450,000

### Army 

Total strength: 21,500

1 task group which includes:

1 armoured regiment and 2 battle groups

1 battalion group in Malaya

1 battalion of the Pacific Islands Regiment

### Navy 

Total strength: 11,000

1 aircraft carrier

12 destroyers and frigates

67 other ships

### Air Force

Total strength: 16,000

12 squadrons including:

3 tactical bomber squadrons

4 fighter squadrons

## NEW ZEALAND

### General

Population: 2,403,000

Voluntary military service

Total armed forces: 12,740

Defence budget: $84,300,000

### Army 

Total strength: 5,340

One brigade group (including 1 battalion in Malaya)

### Navy 

Total strength: 2,900

1 cruiser

4 frigates

15 small ships

### Air Force

Total strength: 4,500

6 squadrons

## PHILIPPINE REPUBLIC

### General 

Population: 24,000,000

Voluntary military service

Total armed forces: 32,000

### Army 

Total strength: 21,500

Navy Total strength: 4,250

60 small ships

Air Force Total strength: 6,250

200 aircraft including 3 squadrons

ofF.86s

## THAILAND

### General 

Population: 25,000,000

2 years military service

Total armed forces: 135,300

### Army 

Total strength: 92,000

5 divisions

### Navy 

Total strength: 21,300

5 frigates

67 small ships

### Air Force

Total strength: 22,000

6 wings, equipped with F.84s and F.86s Transport units


