# TABLE I MOBILIZED MANPOWER

| Western Alliances |  |  |  |  | Communist Bloc |  |  |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| Country |  |  | Total <br> forces | Percentage <br> of male <br> labour <br> force | Country | Total <br> forces | Percentage <br> of male <br> labour <br> force |
| United Stat |  | . | $2,606,000$ | 5.26 | Soviet Union | $3,800,000^*$ | 5.43 |
| France | .. | +. | $1,008,791$ | 7.21 | Poland .. | 255,000 | 2.83 |
| Turkey | .. | .. | 500,000 | 6.25 | Rumania .. | 222,000 | 3.58 |
| Italy .. | .. | .. | 466,392 | 2.91 | Czechosolvakia .. | 185,000 | 4.87 |
| United Kingdom |  | .. | 454,330 | 2.67 | Bulgaria .. | 120,000 | 4.29 |
| Germany | .. | .. | 330,000 | 1.98 | East Germany .. | 100,000 | 2.00 |
| Greece | .. | .. | 159,000 | 5.68 | Hungary .. | 80,500 | 2.30 |
| Netherlands |  | .. | 142,000 | 4.18 | Albania .. : .. | 27,800 | 5.56 |
| Canada | .. | .. | 120,000 | 2.40 |  |  |  |
| Belgium | .. | .. | 110,000 | 3.79 |  |  |  |
| Portugal | .. | .. | 79,000 | 2.26 |  |  |  |
| Norway | .. | .. | 37,000 | 3.08 |  |  |  |
| Denmark | +. | .. | 43,000 | 2.87 |  |  |  |
| Luxembourg |  | .. | 5,500 | 4.78 |  |  |  |
| Total Nato |  | .. | $6,061,013$ | 4.30 | TOTAL WARSAW PACK .. | 4790300 |  |
| Iran .. | .. | * | 210,000 | 3.00 | China .. | 2,600,000+ |  |
| Pakistan | . | .. | 182,700 | .70 | North Korea | 338,000 | * |
| Thailand | .. | . | 135,300 | 1.85 | North Vietnam .. | 266,000 |  |
| Australia | . | . | 48,500 | 1.51 |  |  |  |
| Philippine Repub |  |  | 32,000 | 2.19 | 3 |  | " |
| New Zealand |  | . | 12,740 | 1.42 |  |  |  |
| Total Western Alliances |  | .. | $6,682,235$ | 3.47 |  |  |  |
| Japan | .. | +. | 233,000 | .85 |  |  |  |
| Taiwan | .. | .. | 680,000 | 25.19 |  |  | . |
| South Korea |  | . | $600,000 \dagger$ | 10.91 |  |  |  |
| TOTAL US Powers | Total $\cdots$ | Y | $8,195,253$ | 3.49 | Total Communist <br> Bloc | $7,994,300$ |  |


# SOME COMPARATIVE ESTIMATES OF STRATEGIC STRENGTH EARLY 1962
| Category |  |  |  | WESTERN ALLIANCES | Comamuntst Bloc |
| :---: | :---: | :---: | :---: | :---: | :---: |
| ICBMs <br> MRBMs .. .. <br> Long range bombers <br> Medium range bombers <br> Aircraft carriers <br> Nuclear submarines <br> Conventional submarines <br> Cruisers* .. .. | $\because$ <br> $\cdots$ <br> $\cdots$ <br> $\cdots$ <br> $\cdots$ <br> $\cdots$ <br> $\ldots$ |  |  | 63 <br> 186 <br> 600 <br> 2,200 <br> 58 <br> 22 <br> 266 <br> 67 | $50+$ <br> 200 <br> 190 <br> 1,100 <br> -2 <br> 480 <br> 25 |
| Mobilized manpower | $\therefore$ | .. | .. | $8,195,253$ men | $7,994,300$ men |

Includes ships in reserve

Note on maps (12 and 13).

The term 'deployed manpower' is used to comprise all forces stationed in the countries or areas illustrated irrespective of national origin, including e.g. U.S. forces in German Federal Republic and Soviet forces in East Germany. The figure of 2,000,000 for Western Europe includes French forces in Algeria.

