# Foreword

This is the third annual estimate compiled by the Institute of the nature and size of military forces of the groups of states involved in the Cold War - the Communist bloc (excluding Yugoslavia but including Albania which is still formally a member of the Warsaw Pact) and all those countries with which the United States has mutual defence treaties. The demand for previous editions of this pamphlet has shown that it fills an important gap in public knowledge, and is considered useful as a guide to the strategic balance between the great powers and their allies and of the orders of magnitude involved in the problem of disarmament.

The Institute assumes full responsibility for the facts and judgments which the pamphlet contains. Since not all the countries have been equally co-operative in producing the relevant information, there are some gaps and some estimated figures.

This pamphlet examines the military balance as it existed at the end of October 1961 and as it may change during the ensuing year. However, in view of the number of emergency measures taken on both sides during the summer and autumn of 1961 as a result of the Berlin crisis, some of the figures it contains, par- ticularly of manpower, may not remain accurate throughout the whole of the next twelve-month period. No longer range projections of force levels or weapons have been included.

Manpower strengths given are those of mobilized or regular forces and do not include reserves or militia. Naval strengths are those of active fleets and ships in commission only. The tabular material and the maps at the end should not be regarded as a true guide to the balance of strategic power since they do not reflect important advantages of geography, invulnerability of bases, efficiency, etc., on both sides. They may, however, be found useful in the context of discussions on disarmament.

November 1961

This is the third annual estimate compiled by the Institute of the nature and size of military forces of the groups of states involved in the Cold War - the Communist bloc (excluding Yugoslavia but including Albania which is still formally a member of the Warsaw Pact) and all those countries with which the United States has mutual defence treaties. The demand for previous editions of this pamphlet has shown that it fills an important gap in public knowledge, and is considered useful as a guide to the strategic balance between the great powers and their allies and of the orders of magnitude involved in the problem of disarmament.

The Institute assumes full responsibility for the facts and judgments which the pamphlet contains. Since not all the countries have been equally co-operative in producing the relevant information, there are some gaps and some estimated figures.

This pamphlet examines the military balance as it existed at the end of October 1961 and as it may change during the ensuing year. However, in view of the number of emergency measures taken on both sides during the summer and autumn of 1961 as a result of the Berlin crisis, some of the figures it contains, par- ticularly of manpower, may not remain accurate throughout the whole of the next twelve-month period. No longer range projections of force levels or weapons have been included.

Manpower strengths given are those of mobilized or regular forces and do not include reserves or militia. Naval strengths are those of active fleets and ships in commission only. The tabular material and the maps at the end should not be regarded as a true guide to the balance of strategic power since they do not reflect important advantages of geography, invulnerability of bases, efficiency, etc., on both sides. They may, however, be found useful in the context of discussions on disarmament.

November 1961
