


## CENTRAL TREATY ORGANIZATION

The members of CENTO are Pakistan, Iran, Turkey, and the United Kingdom, with the United States as an associate member. The scope of the Treaty involves co-operation over a wider field than defensive preparation. CENTO does not have an international command structure as NATO does, nor are national forces allocated to it at present. Co-ordination is exercised by a Council of

military deputies including an American representative in Ankara. The main emphasis so far has been on the development of com- munications and air field to give flexibility to the forces available in the area. Strategic deterrent forces could be rapidly deployed in the area by the US 6th Fleet, from SAC bases in Turkey, and from British bases in Cyprus.

## NATIONAL FORCES

'Table 5

Thor: liquid-fuelled IRBM, range 1,500 miles. Matador jet-powered winged missile, range 300-500 miles. Mace: improved version of Mata- dor. Range 350 miles, speed supersonic, nuclear warhead.

## (ii) Air-to-ground

Hound Dog: for use on B.52s. Range 350 miles, speed super- sonic, nuclear warhead. Bullpup: see under Navy.

Bomarc: long-range ram-jet mis- sile interceptor, range 400 miles, speed 1,600-2,000 m.p.h.

## (iii) Surface-to-air

(iv) Air-to-air Genie: missile with a nuclear warhead carried by fighter- interceptors, range 2-4 miles, speed Mach 3.

Falcon: with nuclear or non- nuclear warhead, range 5 miles, speed supersonic.

Marine Corps

Total strength: 177,000. This will be increased to 190,000 in the first half of 1962. Organized in three divisions, each with their own air wing and amphibious support

## CENTRAL TREATY ORGANIZATION

The members of CENTO are Pakistan, Iran, Turkey, and the United Kingdom, with the United States as an associate member. The scope of the Treaty involves co-operation over a wider field than defensive preparation. CENTO does not have an international command structure as NATO does, nor are national forces allocated to it at present. Co-ordination is exercised by a Council of

military deputies including an American representative in Ankara. The main emphasis so far has been on the development of com- munications and air field to give flexibility to the forces available in the area. Strategic deterrent forces could be rapidly deployed in the area by the US 6th Fleet, from SAC bases in Turkey, and from British bases in Cyprus.

## NATIONAL FORCES

'Table 1

# SOUTH-EAST ASIA TREATY ORGANIZATION

The members of SEATO are Australia, France, New Zealand, Pakistan, the Philip- pine Republic, Thailand, the United King- dom and the United States. SEATO does not yet have a centralized command struc- ture and forces remain under national con- trol. SEATO co-operation is concerned not only with military defence against aggression, but also with the problem of subversion.

The main strategic forces are provided by the US Seventh Fleet (see strategic forces,

p\. 9) based on Manila, units of Strategic Air Command based on Okinawa and Guam and the British Far Eastern Fleet based on Singapore.. The Commonwealth Strategic Reserve in Malaya includes British, Austra- lian and New Zealand battalions and sup- porting units, and Australian and New Zealand naval and tactical air units, but the Malay Federation has recently made it clear that bases in Malaya would not be available for SEATO operations.

## NATIONAL FORCES

'Table 1

TABLE I MOBILIZED MANPOWER

'Table 1

-   Maximum

Estimated

TABLE II

# SOME COMPARATIVE ESTIMATES OF STRATEGIC STRENGTH EARLY 1962

'Table 2

'Figure 2

Includes ships in reserve

Note on maps (12 and 13).

The term 'deployed manpower' is used to comprise all forces stationed in the countries or areas illustrated irrespective of national origin, including e.g. U.S. forces in German Federal Republic and Soviet forces in East Germany. The figure of 2,000,000 for Western Europe includes French forces in Algeria.

Erratum. The figures of deployed manpower for Pakistan on the map on page 13 should read 183,000

TABLE II

# SOME COMPARATIVE ESTIMATES OF STRATEGIC STRENGTH EARLY 1962

'Table 1

'Figure 2

Includes ships in reserve

Note on maps (12 and 13).

The term 'deployed manpower' is used to comprise all forces stationed in the countries or areas illustrated irrespective of national origin, including e.g. U.S. forces in German Federal Republic and Soviet forces in East Germany. The figure of 2,000,000 for Western Europe includes French forces in Algeria.

Erratum. The figures of deployed manpower for Pakistan on the map on page 13 should read 183,000
