# FOREWORD

This is the third annual estimate compiled by the Institute of the nature and size of military forces of the groups of states involved in the Cold War - the Communist bloc (excluding Yugoslavia but including Albania which is still formally a member of the Warsaw Pact) and all those countries with which the United States has mutual defence treaties. The demand for previous editions of this pamphlet has shown that it fills an important gap in public knowledge, and is considered useful as a guide to the strategic balance between the great powers and their allies and of the orders of magnitude involved in the problem of disarmament.

The Institute assumes full responsibility for the facts and judgments which the pamphlet contains. Since not all the countries have been equally co-operative in producing the relevant information, there are some gaps and some estimated figures.

This pamphlet examines the military balance as it existed at the end of October 1961 and as it may change during the ensuing year. However, in view of the number of emergency measures taken on both sides during the summer and autumn of 1961 as a result of the Berlin crisis, some of the figures it contains, par- ticularly of manpower, may not remain accurate throughout the whole of the next twelve-month period. No longer range projections of force levels or weapons have been included.

Manpower strengths given are those of mobilized or regular forces and do not include reserves or militia. Naval strengths are those of active fleets and ships in commission only. The tabular material and the maps at the end should not be regarded as a true guide to the balance of strategic power since they do not reflect important advantages of geography, invulnerability of bases, efficiency, etc., on both sides. They may, however, be found useful in the context of discussions on disarmament.

November 1961

## Contents

'Table 1

# PART I. THE COMMUNIST POWERS

## THE SOVIET UNION (Population 218 million)

## General

Throughout 1960 and the first half of 1961 the Soviet military policy followed the same course as that pursued by the United States in the mid-1950s and by Britain after 1957: an attempt was made to absorb the cost of technological development and new weapons by placing increased emphasis on nuclear fire power and reducing the amount of mobilized manpower. It was clear that the Soviet government had, at the end of 1959, reached a considered decision that their progress in missile technology, coupled with the demands of the economy, especially agriculture, for more men, justified such a policy. However, during July 1961, the Soviet government announced, in response to its own estimate of a darkening inter- national horizon, a revision of this emphasis on the deterrent effect of nuclear missiles, and has been anxious since then to make clear that it is building up the strength of virtually all its forces except surface ships. Under the law of January 15, 1960, the Soviet forces were to be reduced from 3,623,000 men to 2,423,000 men by the end of 1961, a reduction of 1,200,000 men over two years, but its suspension was announced on July 8, 1961. No official Soviet figures of the current strength of the forces has been published but it is not likely that more than 600,000 men were demobilized, principally in the ground forces. Thus the total strength of the forces in mid-1961 was about 3,000,000 men. In addition, it was announced on August 29, 1961, that the demobilization of certain categories of other ranks, whose period of military service was completed, had been suspended until the signature of a German peace treaty. When men called up in 1961 have completed their training and been absorbed into units at the end of the year, the effect of this decree (unless it is rescinded) will be to increase the size of the Soviet forces by up to 800,000 men, giving

a total strength of perhaps 3,800,000 men - some five per cent larger than at the end of 1959.

The Soviet military budget for 1961 (calendar year) was set at 9,255 million roubles ($10,180 million) but it was an- nounced on July 8, 1961, that it would be increased by one-third, i.e. 3,114 million roubles ($3,415 million) to 12,339 million roubles ($13,573 million). In real terms, the total size of the augmented Soviet budget is estimated to be of the order of between $20,000 and $25,000 million. It is not likely that all this one-third increase can be spent during 1961, and only part of it will be needed to meet the increased bill for man- power; this suggests that it is also intended to accelerate weapons development and production.

## Air and Missile Power

Soviet policy statements continue to place marked emphasis on the development of long range missiles as a deterrent to aggres- sion and a support to diplomacy. It is con- sidered possible that the Soviet Union could, if the programme had rated a high enough priority, have by now built up a force of 200 ICBMs, the original three-stage liquid- fuelled missile which has been under devel- opment since the mid-fifties. The reasons that make it doubtful if they have actually created an operational force of this size are:



(a) the difficulties of building bases for so large a missile and their strategic vulnerability:

(b) the fact that they now have a smaller second generation ICBM under active development which is likely to be easier to conceal:

(c) the demands of the Soviet space and other programmes upon scientific man- power:

Consequently the present figure of opera- tional ICBMs is more likely to be in the neighbourhood of 50 than 200.

Unlike the United States Soviet policy places considerable emphasis on conceal-

ment of bases. Apart from the two main missile test centres near the Caspian Sea, it can be assumed only that the location of ICBM sites are influenced by the rail com- munications network.

As far as MRBMs are concerned, the figure of 200 has been quoted in the West, and in view of Soviet concentration on MRBMs this estimate seems reasonable. Soviet state- ments allege that they exist in considerable quantities, and since there are not the same indications of a need to decelerate their build-up in order to make room for a more advanced type as with ICBMs, this is very probably the case. From their ranges and from published Soviet statements, it is reasonably clear that Soviet policy is to site them near the western, southern and eastern borders of the Soviet Union, on the Pacific coast and in Siberia, so that they cover the main bases of Western medium range air and missile power from Britain to Okinawa and Japan.

The strategic missile forces are organized as an autonomous arm of the service, under the command of Marshal Kiril Moskalenko. In July 1961 Marshal Malinovsky, the Soviet Defence Minister, spoke of the reorganiza- tion of the Soviet forces to create tactical missile units capable of operating inde- pendently.

In spite of their concentration on rockets and ballistic missiles, the Russians have not neglected their Air Force, which comprises some 15,000 operational aircraft, organized into five major components, namely:



(1) the long-range strategic bomber force;

(2) the tactical, or front line, force which includes fighters and tactical bombers;

(3) the fighter interceptor force;

(4) the land-based fleet air arm;

(5) the air transport force.

The heavy bomber force has been kept at a considerably lower strength than that of the US Strategic Air Command, though the general lines of development, including stand-off bombs and missiles, are similar. On the other hand the Soviet Union has built up a very strong force of medium bombers suitable for use all over the Eurasian theatre and its coasts, and an efficient light bomber force. It seems probable that, partly

as a result of service and industrial pressure, higher priority is being given to aircraft development than in the late fifties. The following gives some indication of Soviet strength in this field.

## (i) Strategic Striking Power

Missiles



(a) The principal operational ICBM is propelled by a three-stage liquid fuel engine and has an operational range of up to 8,000 miles.

A second generation ICBM is now being developed. It is propelled by a storable liquid fuel and will probably be smaller and more accurate than its predecessor, but still more bulky than the US Minuteman.

(b) There are two operational IRBMs. One has a range of about 1,800 miles and is propelled by a two-stage liquid fuel engine: the other has a range of about 1,000 miles, is also liquid fuelled, and can carry a 1,800 lb atomic warhead.

## Long-range and Medium Bombers

The Strategic Bomber Force consists mainly of the following aircraft:



(a) 70 turbo-prop Bears* (TU 20); range 7,000 miles, bomb-load 20 tons, maximum speed 550 miles per hour, now able to carry two short range air to ground missiles similar to US Hound Dog.

120 4-jet Bisons; range 6,050 miles, bomb- load 10 tons, maximum speed 600 miles per hour, operational ceiling 50,000.

(b) 1,000 twin-jet medium bomber Badgers (TU 16); range 3,500 miles, bomb-load 4-5 tons, speed 587 miles per hour, operational ceiling 40,000 feet. Delta-wing 4-jet Bounder (similar to but somewhat larger than the US B58), speed supersonic (probably Mach 2), range 1,650 miles; said to be capable of using grass runways; prototype displayed in 1961. New types shown at Tushino Air Show in 1961 included nine of a medium bomber, Blinder, somewhat similar to the US B58 and probably being developed for use with a longer range air to ground missile com-

It should be made clear that this menagerie of names for Soviet aircraft is of NATO, not Soviet, origin.

parable to Skybolt, and capable of air refuelling.

A small proportion of this force is based on the Kola peninsula and in Siberia, while the rest is based in western and south-west Russia. Bisons and Badgers have also been adapted as tankers for in-flight refuelling.

## (ii) Tactical Air Power

It is clear that the tactical bomber forces are going through a much sharper period of transition than the heavy bomber forces, with older aircraft such as the turbo-jet Beagle and possibly the twin-jet Blowlamp and Backfin, being replaced. The earlier estimate of 4,000 operational aircraft is therefore now too high. The principal tactical bombers under development had been (a) the supersonic twin-jet Blowlamp, comparable to the RAF Canberra, with a high altitude range of 745 miles and a speed of 750 miles per hour (this was not displayed at the 1961 Air Show), and the twin-jet Backfin with a speed of 800 miles per hour.

Effort now seems to be concentrated on a new twin-jet ground attack aircraft with transonic capabilities and a wide radius of action which, like the new all-weather fighter, seems to be an improved version of Flash- is provisionally known as Flashlight B.

## (iii) Air Defence

The number of ground-to-air guided mis- siles and high-performance fighters for air defence has been steadily increased and an extensive early warning system is in operation. The following are details of air defence equipment:

## Ground-to-Air Guided Missiles

A radar-directed rocket, which is already in service and is considered to be highly effective. It is propelled by one main and one auxiliary solid fuel engine. Its slant range is 20 miles, and it rises to a height of 12 miles (60,000 feet).

There may also be a high-altitude guided missile with radio guidance, and there is an anti-aircraft missile which has a range of 18 miles and speed over 1,500 miles per hour.

## Fighter Planes

It is estimated that there are about 10,000 fighter aircraft of all kinds, and that intensive development is in hand to produce types with higher ceilings and improved air-to-air weapons.

(a) The standard all-weather interceptor of recent years, the subsonic Yak 25 Flash- light, is now obsolescent, although two improved versions, one of them redesigned as a light bomber, are still in service. How- ever a new all-weather delta-winged inter- ceptor provisionally called Flashlight C, was displayed in July 1961.

'Table 1

In April 1961 the Soviet Union claimed a world height record of 110,000 feet for a delta-winged "E 66" which was almost cer- tainly Fishbed. (The official world record of 103,000 feet is still held by a US F102.)

## Land Power

No official figures of the Soviet Army have been published but with the partial arresting of demobilization and the retention of the 1961 conscripts its total size is estimated at up to 2,500,000 (an increase of 250,000 on 1960). As a result of this year's special measures it is organized in approximately 160 active line divisions (not all at full strength). An infantry division at war strength com- prises 12,000 men, an armoured division about 10,500 plus supporting artillery and anti-aircraft units.

Most of the active divisions are armoured or mechanized.

In East Germany there are 10 tank divisions each with 400 tanks, and 10 mech- anized divisions, each with 250 tanks. All are operational and comprise a total of over 6,000 tanks. In Hungary and Poland there are 6 divisions. It is estimated that the Soviet Union has a total mobilization

potential of 7 million men including all types of reservists.

The airborne forces of the Soviet Union total approximately 100,000 men formed in 9 divisions. The airborne troops are sup- ported by the transport fleet, which would enable about two divisions to be air-dropped or air-landed in any single operation.

In recent years, the Soviet Army has undergone a major reorganization to meet conditions of atomic warfare. Many of its units have been completely re-equipped twice over in the last ten years and, thanks to the introduction of modern weapons, its fire power has been vastly increased. Though the Soviet Union has not shown as much interest as the United States in the development of very low yield nuclear weapons for tactical purposes, nuclear warheads are available for many of the missiles mentioned below. Mr Khrushchev has hinted broadly that the Soviet forces in East Germany have tactical nuclear weapons.

Soviet Army equipment includes:

## (i) Tanks

The total tank strength of the Soviet Army is estimated at 20,000 front-line tanks and 15,000 second-line tanks. The new tanks which have been introduced into the Soviet armoured divisions are the T.54 medium tank, fitted with a 100 mm. gun, and the 54-ton heavy tank T.10, which mounts a 122 mm. gun.

## (ii) Artillery

The Soviet Army is very strong in artillery. Artillery weapons include the atomic 203 mm. cannon mounted on mobile platforms, with a range of 15 miles; and 240 mm. heavy mortars or unguided rockets with a range of 20 miles, together with many other types of mortars. Though many artillery tasks are to be performed by missiles, the Soviet Army still considers that many im- portant functions remain for rifled artillery.

## (iii) Missiles

An improved version of the German V2 ballistic rocket is the standard equipment of

the tactical units. Propelled by one liquid fuel engine, it has a range of 450 miles. It can be fired from a mobile ramp, is radio guided and can carry a nuclear warhead. There is a solid fuel ballistic missile with a range of 50 miles, which may be obsolete, and two smaller versions, carried on self- propelled launchers with ranges from 10 to 15 miles (equivalent to US Honest John). There is also a truck-launched missile with a range of 50 miles, which fires an HE warhead. A range of anti-tank missiles has also been developed.

## Sea Power

The Soviet Navy, which is manned by about 500,000 officers and men, has increased from a total tonnage in 1940 of 600,000 to 1,600,000 tons today, which makes it the most powerful fleet in the world after the United States (4 million tons).

## (i) Submarines

The main strength of the Soviet Navy lies in the submarine fleet.

The submarine force is generally estimated to comprise at least 430 units, of which 85 are based in the Baltic, 65 in the Black Sea, 140 in the Arctic, 120 in the Far East. Eight formerly based in the Mediterranean, on the Albanian ports of Durazzo and Valona, have been withdrawn. It is expected that in the foreseeable future, 75 per cent of the submarine fleet will con- sist of ocean-going craft of which a propor- tion will be atomic powered. At the moment, Russia has 6 atomic powered submarines in various stages of construction of which one or two may be at sea. The following are details of the conven- tionally powered submarine fleet: The F class is about 300 feet long, has a displacement of 2,000 tons, and a large radius of action. At least 10 of these are in service. The G class is 310 feet long and has a submerged displacement of 2,700 tons. It has a very large conning tower for the vertical launching of an unknown number of missiles which are fired when on the surface.

2A

The W class is 245 feet long with a 1,050 tons displacement. It has a speed of 16 knots on the surface and 13 knots submerged, and a radius of action of 10,000 miles. There are about 130 of these in service. The Z class is 290 feet long with a sub- merged displacement of 2,600 tons. It is capable of 20 knots on the surface and 13 knots submerged, with a radius in excess of 20,000 miles. There are at least 20 of these in service. A small number have been con- verted to fire missiles, probably in a manner similar to the G class. They are stationed principally in the Baltic and the Far East. The K and Q type, which were built between 1945 and 1955, are medium range vessels; their radius of action is about 7,000 miles and their displacement varies from 1,400 to 680 tons.

The surface ships of the Soviet Navy consist of : Cruisers 25 Destroyers 130 Other vessels 2,500 (There are also a number of disguised trawlers used for radar and recon- naissance purposes.) These are distributed more or less equally between the Baltic, Black Sea, Northern and Pacific fleets.

'Table 2

The cruisers are of three different types:



(a) 17 Sverdlov, launched between 1951 and 1957, displacement 15,500 tons, speed 34 knots, armament 12 152 mm. guns and 32 anti-aircraft guns;

(b) 5 Chapayev class, completed between 1948 and 1951, of 11,500 tons displacement, with the same speed and armament as the Sverdlov;

(c) 6 Kirov and Gorki class, launched between 1936 and 1945, displacement 8,500 tons, speed 30 knots, armament 9 180 mm. guns and 20 anti-aircraft guns.

Four or more almost completed Sverdlov cruisers appear to have been scrapped.

Their displacement varies from 1,000 to 2,700 tons, and their speed from 28 to 38 knots.

The greater part of the destroyers are modern, having been constructed since 1950, and some are fitted with guided missiles.

## (iii) Fleet Air Arm

There are no aircraft carriers in the Soviet Navy, but there is a land-based Fleet Air Arm which now appears to be getting a lower priority than formerly. It consists mainly of:



(a) the torpedo-carrying IL 28 Beagle and TU 14 Bosun with ranges of 1,500-1,800 miles;

(b) the TU 16 Badger - range of 3,500 miles.

## (ii) Surface Ships

A new twin-jet swept-wing flying boat and an anti-submarine turbine helicopter with a short range missile were displayed in 1961.

## (iv) Sea-to-ground Missiles

## THE WARSAW PACT NATIONS

There are believed to be two types. One has a range of about 100 miles and the other of about 400 miles. The 100 miles range missile is believed to be solid fuelled and can be fired either from a surface craft or a surfaced submarine. The 400-mile missile is designed for submarines but can only be fired from the surface.

Soviet claims to have an equivalent of the Polaris missile, which can be fired from a submerged submarine, are misleading.

It is estimated that the seven Soviet satellites can muster about 68 regular divisions, mainly of the conventional type. These satellites' armed forces represent a total of about 990,300 men under arms (a significant in- crease over 1960), and in addition there are about 360,000 men in paramalitary forma- tions.

The following are the estimated strength of their armed forces with their total popu- lation in brackets:

'Table 3

The W class is 245 feet long with a 1,050 tons displacement. It has a speed of 16 knots on the surface and 13 knots submerged, and a radius of action of 10,000 miles. There are about 130 of these in service. The Z class is 290 feet long with a sub- merged displacement of 2,600 tons. It is capable of 20 knots on the surface and 13 knots submerged, with a radius in excess of 20,000 miles. There are at least 20 of these in service. A small number have been con- verted to fire missiles, probably in a manner similar to the G class. They are stationed principally in the Baltic and the Far East. The K and Q type, which were built between 1945 and 1955, are medium range vessels; their radius of action is about 7,000 miles and their displacement varies from 1,400 to 680 tons.

## (ii) Surface Ships



The surface ships of the Soviet Navy consist of :

(There are also a number of disguised trawlers used for radar and recon- naissance purposes.)

These are distributed more or less equally between the Baltic, Black Sea, Northern and Pacific fleets.

'Table 1

The cruisers are of three different types:



(a) 17 Sverdlov, launched between 1951 and 1957, displacement 15,500 tons, speed 34 knots, armament 12 152 mm. guns and 32 anti-aircraft guns;

(b) 5 Chapayev class, completed between 1948 and 1951, of 11,500 tons displacement, with the same speed and armament as the Sverdlov;

(c) 6 Kirov and Gorki class, launched between 1936 and 1945, displacement 8,500 tons, speed 30 knots, armament 9 180 mm. guns and 20 anti-aircraft guns.

Four or more almost completed Sverdlov cruisers appear to have been scrapped.

The greater part of the destroyers are modern, having been constructed since 1950, and some are fitted with guided missiles.

Their displacement varies from 1,000 to 2,700 tons, and their speed from 28 to 38 knots.

## (iii) Fleet Air Arm

There are no aircraft carriers in the Soviet Navy, but there is a land-based Fleet Air Arm which now appears to be getting a lower priority than formerly. It consists mainly of:



(a) the torpedo-carrying IL 28 Beagle and TU 14 Bosun with ranges of 1,500-1,800 miles;

(b) the TU 16 Badger - range of 3,500 miles.

A new twin-jet swept-wing flying boat and an anti-submarine turbine helicopter with a short range missile were displayed in 1961.

## (iv) Sea-to-ground Missiles

There are believed to be two types. One has a range of about 100 miles and the other of about 400 miles. The 100 miles range missile is believed to be solid fuelled and can be fired either from a surface craft or a surfaced submarine. The 400-mile missile is designed for submarines but can only be fired from the surface.

Soviet claims to have an equivalent of the Polaris missile, which can be fired from a submerged submarine, are misleading.

## THE WARSAW PACT NATIONS

It is estimated that the seven Soviet satellites can muster about 68 regular divisions, mainly of the conventional type. These satellites' armed forces represent a total of about 990,300 men under arms (a significant in- crease over 1960), and in addition there are about 360,000 men in paramalitary forma- tions.

The following are the estimated strength of their armed forces with their total popu- lation in brackets:

'Table 2

East Germany* (16,213,000) 100,000 Hungary (10,002,000) 80,500 Albania (1,607,000) 27,800

The satellite air forces number a total of about 2,900 planes, about 80 per cent of which are jet fighters.

The satellite naval forces are of little importance and only of value for local defence.

## CHINA

The Army



(i) The Army consists of 2,216,000 men, organized in: approximately 115 divisions of infantry; 2 or 3 armoured divisions; 1 or 2 airborne divisions; supporting troops; and cavalry for desert areas.

There are 125,000,000 men of military age in 1961. About 700,000 are called up each year, and serve three years in the Army.

(ii) The armed forces are organized by the Ministry of Defence, advised by a National Defence Council whose Chairman is the Chairman of the People's Republic: control is exercised through 13 Military Regions. The Land Army consists of about 30-35 armies. These are of 3 divisions each, i.e. an Army is equivalent to a Western Army Corps. In peacetime there is no operational headquarters higher than the Army; but in wartime Armies are grouped in Field Armies. The strength of an active Army could be between 50,000-60,000.

(iii) No reliable figures are available for the size of the Militia, but the declared inten-

* The population of East Germany is 17,298,000 if East Berlin is included. The figure for its armed forces may rise markedly during the coming year as a result of conscription and if para-military formations such as the 75,000 man Bereitschaftspolizei are incorporated into the regular forces.

tion is to embody every third person in the population. It is static, sketchily armed, and organized as much for forced labour as defence. The Public Security forces, includ- ing the armed police, consist of about 200,000 men.

The Air Force

This has a total strength of 3,000 aircraft, including 400 naval aircraft. China is now building jet fighters and trainers, but the backbone of the force consists of Soviet MIG 15s, 17s and probably 19s, IL 28 light bombers and helicopters. Training is in- hibited by shortage of aviation spirit.

## The Navy

China has no operational ships heavier than destroyers, of which there are 4. There are 26 submarines (a small increase on 1960), of which half are Soviet W class medium range craft; frigates; MTBs; gun- boats and patrol craft. The Navy is not an offensive force and is ineffective except for inshore defence.

THE FAR EAST

NORTH KOREA

The Soviet Union concluded a mutual defence treaty with North Korea on July 7, 1961. The North Korean forces are estimated at 338,000 men.

## NORTH VIETNAM

Both the Soviet Union and China assist in the support of a strong army which is estimated at 266,000 men.

East Germany* (16,213,000) 100,000 Hungary (10,002,000) 80,500 Albania (1,607,000) 27,800

The satellite air forces number a total of about 2,900 planes, about 80 per cent of which are jet fighters.

The satellite naval forces are of little importance and only of value for local defence.

## CHINA

The Army



(i) The Army consists of 2,216,000 men, organized in: approximately 115 divisions of infantry; 2 or 3 armoured divisions; 1 or 2 airborne divisions; supporting troops; and cavalry for desert areas.

There are 125,000,000 men of military age in 1961. About 700,000 are called up each year, and serve three years in the Army.

(ii) The armed forces are organized by the Ministry of Defence, advised by a National Defence Council whose Chairman is the Chairman of the People's Republic: control is exercised through 13 Military Regions. The Land Army consists of about 30-35 armies. These are of 3 divisions each, i.e. an Army is equivalent to a Western Army Corps. In peacetime there is no operational headquarters higher than the Army; but in wartime Armies are grouped in Field Armies. The strength of an active Army could be between 50,000-60,000.

(iii) No reliable figures are available for the size of the Militia, but the declared inten-

* The population of East Germany is 17,298,000 if East Berlin is included. The figure for its armed forces may rise markedly during the coming year as a result of conscription and if para-military formations such as the 75,000 man Bereitschaftspolizei are incorporated into the regular forces.

tion is to embody every third person in the population. It is static, sketchily armed, and organized as much for forced labour as defence. The Public Security forces, includ- ing the armed police, consist of about 200,000 men.

## The Air Force

This has a total strength of 3,000 aircraft, including 400 naval aircraft. China is now building jet fighters and trainers, but the backbone of the force consists of Soviet MIG 15s, 17s and probably 19s, IL 28 light bombers and helicopters. Training is in- hibited by shortage of aviation spirit.

## The Navy

China has no operational ships heavier than destroyers, of which there are 4. There are 26 submarines (a small increase on 1960), of which half are Soviet W class medium range craft; frigates; MTBs; gun- boats and patrol craft. The Navy is not an offensive force and is ineffective except for inshore defence.

THE FAR EAST

NORTH KOREA

The Soviet Union concluded a mutual defence treaty with North Korea on July 7, 1961. The North Korean forces are estimated at 338,000 men.

## NORTH VIETNAM

Both the Soviet Union and China assist in the support of a strong army which is estimated at 266,000 men.

East Germany* (16,213,000) 100,000 Hungary (10,002,000) 80,500 Albania (1,607,000) 27,800

The satellite air forces number a total of about 2,900 planes, about 80 per cent of which are jet fighters.

The satellite naval forces are of little importance and only of value for local defence.

## CHINA

The Army



(i) The Army consists of 2,216,000 men, organized in: approximately 115 divisions of infantry; 2 or 3 armoured divisions; 1 or 2 airborne divisions; supporting troops; and cavalry for desert areas.

There are 125,000,000 men of military age in 1961. About 700,000 are called up each year, and serve three years in the Army.

(ii) The armed forces are organized by the Ministry of Defence, advised by a National Defence Council whose Chairman is the Chairman of the People's Republic: control is exercised through 13 Military Regions. The Land Army consists of about 30-35 armies. These are of 3 divisions each, i.e. an Army is equivalent to a Western Army Corps. In peacetime there is no operational headquarters higher than the Army; but in wartime Armies are grouped in Field Armies. The strength of an active Army could be between 50,000-60,000.

(iii) No reliable figures are available for the size of the Militia, but the declared inten-

* The population of East Germany is 17,298,000 if East Berlin is included. The figure for its armed forces may rise markedly during the coming year as a result of conscription and if para-military formations such as the 75,000 man Bereitschaftspolizei are incorporated into the regular forces.

tion is to embody every third person in the population. It is static, sketchily armed, and organized as much for forced labour as defence. The Public Security forces, includ- ing the armed police, consist of about 200,000 men.

## The Air Force

This has a total strength of 3,000 aircraft, including 400 naval aircraft. China is now building jet fighters and trainers, but the backbone of the force consists of Soviet MIG 15s, 17s and probably 19s, IL 28 light bombers and helicopters. Training is in- hibited by shortage of aviation spirit.

## The Navy

China has no operational ships heavier than destroyers, of which there are 4. There are 26 submarines (a small increase on 1960), of which half are Soviet W class medium range craft; frigates; MTBs; gun- boats and patrol craft. The Navy is not an offensive force and is ineffective except for inshore defence.

THE FAR EAST

## NORTH KOREA

The Soviet Union concluded a mutual defence treaty with North Korea on July 7, 1961. The North Korean forces are estimated at 338,000 men.

## NORTH VIETNAM

Both the Soviet Union and China assist in the support of a strong army which is estimated at 266,000 men.

PART II.

THE WESTERN ALLIANCES

# STRATEGIC FORCES

These are under national command and comprise the United States Strategic Air Command, RAF Bomber Command, the United States First and Seventh Fleets and the United States nuclear powered sub- marines, equipped with the Polaris missiles. In addition, IRBM bases in Europe are in operation or under construction. Exceptions to the nationally controlled strategic forces are the NATO controlled Striking Fleet Atlantic, which is also nationally designated the US Second Fleet and the NATO Carrier Striking Force, South, which is nationally designated the US Sixth Fleet, operating in the Mediterranean. An essential component of the strategic forces of the West is its air and missile warning systems.

## (1) United States Air and Missile Bases

The chief concern of United States defence in the eventuality of a general war will be a surprise attack by nuclear-armed ICBMs. For this, it is developing forces which can survive and respond to a first attack. Strategic Air Command is divided into



(a) the Fifth Air Force with Headquarters in California, and the Second and Eighth Air Force with Headquarters in Louisiana and Massachusetts.

(b) the First Missile Division with Head- quarters in California.

(c) the 16th Air Force in Spain, the 7th Air Division in the UK, and the 3rd Air Division based on Guam. Each of these overseas units operates several advance bases.

Strategic Aircraft. The SAC has over 1,500 bombers capable of delivering nuclear bombs. Of these, some 1,000 are B.47s, and 600 are long-range B.52s based in the United States. Both types of aircraft use in-flight refuelling to extend their range. The B.58,

of which there are between thirty and forty now in service, will partially replace the B.47.

One-third of these forces is now kept con- tinuously on 'ground alert', which will enable them to leave their bases within 15 minutes of receiving warning of attack. The propor- tion is to be increased to one-half by the middle of 1962.

Missiles. The First Missile Division oper- ates the Atlas and Titan ICBMs. The present long-term programme comprises 25 Atlas and Titan squadrons, including 6 Atlas squadrons with 12 missiles permanently on launchers. By early in 1962 three main bases of the present 'soft' Vandenberg and Warren types will have been completed. By then there will also be one 'hard' Titan base (at Denver, Colorado) and two more 'semi-hard' Atlas bases. This will mean that 54 Atlas and nine Titans are operational.

The Snark guided missile is to be with- drawn by the end of 1961.

The Minuteman, a solid propellant ICBM, capable of being mounted on a mobile base (though the first six squadrons are to be based on fixed sites), will not be operational until late in 1962.

## (2) RAF Bomber Command

RAF Bomber Command is equipped with about 180 Vulcan, Valiant and Victor bombers, capable of carrying free falling nuclear or conventional bombs. They are able to refuel in flight from Valiant jet tankers. (It is now doubtful if the guided stand-off bomb Blue Steel, with a range of 400 miles, will be available in 1962.)

## (3) European Missile Bases

There are sixty Thor IRBMs based in the United Kingdom. Work on the site for 30 Jupiter IRBMs in Italy is scheduled to be completed by the end of 1961. There is no

evidence that work on the site for 15 more Jupiters in Turkey is proceeding.

## (4) Seapower

Surface Ships



(a) The United States 1st, 2nd, 6th and 7th Fleets each comprise about fifty ships and have aircraft carriers as a nucleus. The US First Fleet is based on the west coast of the United States, ready to be deployed separately or to augment the US Seventh Fleet in the Far East on a national basis.

The other western nations have six air- craft carriers in the Atlantic area, and Britain's will shortly have a nuclear strike capability.

(b) The United States nuclear powered submarine force, armed with the IRBM Polaris, is now operational. Six submarines, each equipped with 16 missiles, will be com- missioned by the end of 1961, and a further 3 by the end of 1962. The A.2, an improved version of the Polaris, with a range of 1,500 miles, is soon to be in production.

## (5) Warning Systems

(a) BMEWS. Two Ballistic Missile Early Warning System stations are in operation in Greenland and Alaska. The third station, at Fylingdales, Yorkshire, will be completed early in 1962. These will provide fifteen minutes' warning for that part of the SAC force which is to be kept on ground alert.

(b) MIDAS. The development of the Missile Defence Alarm System satellite is to be accelerated. This will provide thirty minutes' warning, which BMEWS would

then serve to confirm. Fylingdales is also to have a reception system for MIDAS signals.

## (6) Strategic Reserves

United States: The Strategic Army Corps, which forms the main element of the United States strategic reserve, consists of two airborne divisions and one infantry division, totalling some 110,000 men. The infantry division is supported by elements armed with the Honest John field missile. There is a possibility that one of these divisions will be sent to join the 7th Army in Europe, in which case it would be replaced in the US by a National Guard division. The President has announced his intention of adding 3 divisions to the Continental Army Com- mand and assigning them to STRAC by the middle of 1962.

The total number of men in the US Continental Army Command is at present about 250,000.

United Kingdom: The elements of the Strategic Reserve which are assigned for reinforcement of the BAOR consist of the main part of the Parachute Brigade based in the UK, which will operate in association with some infantry battalions, and a division of two infantry brigades at present being built up in England.

France: There are now two divisions stationed in France and two in Algeria. These are considered as reinforcements for the Central Area of NATO in the event of hostilites.

Canada: Two brigade groups stationed in Canada are earmarked for the Supreme Commander in the event of hostilities.

## NORTH ATLANTIC TREATY ORGANIZATION

## (A) Allied Command, Europe

Allied Command has its headquarters near Paris and stretches from northern Norway to the southern frontiers of Turkey and the Mediterranean. The Air Forces in Europe of

the NATO Powers can muster 5,000 tac- tical aircraft which operate from some 220 operational bases. Nearly 5,000 miles of fuel supply systems are in service for the supply of the forces, 26,500 miles of com-

evidence that work on the site for 15 more Jupiters in Turkey is proceeding.

## (4) Seapower

Surface Ships



(a) The United States 1st, 2nd, 6th and 7th Fleets each comprise about fifty ships and have aircraft carriers as a nucleus. The US First Fleet is based on the west coast of the United States, ready to be deployed separately or to augment the US Seventh Fleet in the Far East on a national basis.

The other western nations have six air- craft carriers in the Atlantic area, and Britain's will shortly have a nuclear strike capability.

(b) The United States nuclear powered submarine force, armed with the IRBM Polaris, is now operational. Six submarines, each equipped with 16 missiles, will be com- missioned by the end of 1961, and a further 3 by the end of 1962. The A.2, an improved version of the Polaris, with a range of 1,500 miles, is soon to be in production.

## (5) Warning Systems

(a) BMEWS. Two Ballistic Missile Early Warning System stations are in operation in Greenland and Alaska. The third station, at Fylingdales, Yorkshire, will be completed early in 1962. These will provide fifteen minutes' warning for that part of the SAC force which is to be kept on ground alert.

(b) MIDAS. The development of the Missile Defence Alarm System satellite is to be accelerated. This will provide thirty minutes' warning, which BMEWS would

then serve to confirm. Fylingdales is also to have a reception system for MIDAS signals.

## (6) Strategic Reserves

United States: The Strategic Army Corps, which forms the main element of the United States strategic reserve, consists of two airborne divisions and one infantry division, totalling some 110,000 men. The infantry division is supported by elements armed with the Honest John field missile. There is a possibility that one of these divisions will be sent to join the 7th Army in Europe, in which case it would be replaced in the US by a National Guard division. The President has announced his intention of adding 3 divisions to the Continental Army Com- mand and assigning them to STRAC by the middle of 1962.

The total number of men in the US Continental Army Command is at present about 250,000.

United Kingdom: The elements of the Strategic Reserve which are assigned for reinforcement of the BAOR consist of the main part of the Parachute Brigade based in the UK, which will operate in association with some infantry battalions, and a division of two infantry brigades at present being built up in England.

France: There are now two divisions stationed in France and two in Algeria. These are considered as reinforcements for the Central Area of NATO in the event of hostilites.

Canada: Two brigade groups stationed in Canada are earmarked for the Supreme Commander in the event of hostilities.

## NORTH ATLANTIC TREATY ORGANIZATION

## (A) Allied Command, Europe

Allied Command has its headquarters near Paris and stretches from northern Norway to the southern frontiers of Turkey and the Mediterranean. The Air Forces in Europe of

the NATO Powers can muster 5,000 tac- tical aircraft which operate from some 220 operational bases. Nearly 5,000 miles of fuel supply systems are in service for the supply of the forces, 26,500 miles of com-

munications and signal network are in use, and an effective early warning radar system has been developed. Deployment of tactical nuclear weapons into NATO land forces is now almost complete. They are principally the Honest John missile, but include some Corporals and 280 mm. cannon. Joint pro- duction in European NATO countries of two anti-aircraft weapons Hawk and Side- winder is continuing, as well as three types of aircraft, the F104G Starfighter, the Breguet Atlantic, and the Fiat G91 light fighters.

Allied Command Europe is divided into the following subordinate commands:



(i) Allied Forces Central Europe has its headquarters in Fontainebleau and com- prises 23 divisions (out of the required 30) assigned to the Supreme Commander as follows:

Out of these forces, a small mobile task force of 5 battalions with a nuclear capa- bility has been created as a tactical reserve for NATO as a whole.

The tactical air forces available in the central area consist of some 3,000 aircraft, of which 250 US fighter-bombers and a smaller number of British Canberras, now being replaced by Vulcan 2s, and Valiants have a nuclear capability and a range which would cover important sections of eastern Russia.

The tactical air forces are organized into two main commands, 2nd ATAF (under British command) in northern Germany, which includes British, Dutch, Belgian and

'Table 1

German forces; 4th ATAF (under Ameri- can command) in southern Germany, in- cludes American, Canadian, French and German forces.



(ii) Allied Forces Northern Europe has its headquarters at Kolsaas in Norway and is responsible for the defence of Norway, Denmark, Schleswig-Holstein and the Baltic approaches. It comprises approximately one Norwegian and one Danish division, as well as the tactical air forces of these countries and their naval forces. One German division in Schleswig-Holstein and units of the German Baltic fleet are also committed to AFNORTH.

(iii) Allied Forces Southern Europe has its headquarters in Naples and is responsible for the defence of the Mediterranean NATO area. The forces allocated to this command comprise 14 divisions from Tur- key, 9 from Greece and 7 from Italy, as well as the tactical air forces of these countries which comprise some 1,000 aircraft, and some naval forces. US forces in Italy and Greece also operate some Honest John guided missile units in conjunction with national forces. The US Sixth Fleet would come under command of AFSOUTH in time of war.

(iv) Allied Forces Mediterranean has its headquarters at Malta and is primarily responsible for safeguarding communica- tions through and across the Mediterranean. Six areas are under national control, two British, one French, one Italian, one Greek, one Turkish. There is also a special subor- dinate command for submarine forces in the Mediterranean. The national fleets of Italy, Greece and Turkey, together with a propor- tion of the British and - normally the French fleets, go to make up this command.

## (B) Allied Command, Atlantic

Unlike the Supreme Allied Commander Europe, the Supreme Allied Commander Atlantic does not have forces permanently

assigned to him in peacetime. The eight NATO maritime powers bordering the Atlantic maintain control of their forces in peacetime, but have earmarked certain of them for SACLANT in the event of war.

Broadly speaking, in wartime, SACLANT's missions are to strike at enemy naval bases and airfields with aircraft from the Striking Fleet Atlantic, to main- tain control of the Atlantic sea lanes, to prevent enemy forces from striking at European and North American land bases from the sea, and to support the Allied Command Europe. To the Striking Fleet Atlantic would be assigned a considerable proportion of American and British attack aircraft carriers.



(1) The surface ships in the navies of the eight Atlantic maritime nations include about 25 aircraft carriers. Of these, six American carriers have been converted for anti-submarine duties. Britain has 3 carriers, France, Canada and the Nether- lands have one each. The carriers designated for anti-submarine missions carry American and/or Canadian S2F Trackers, British Fairey Gannets, largely replaced by Sea Vixens, and Scimitars and Wessex helicopters, French 1050 Alizes and anti-submarine helicopters. In all, NATO anti-submarine carriers could embark about 400 to 500 aircraft of various types.

(2) Other surface ships in these national navies include about 440 destroyers, frigates and destroyer escorts. (The United States has over 260 of these types, the Royal Navy has over 47 to contribute, while the other navies have lesser numbers.) A considerable proportion of these anti-submarine ships are of World War II construction but many have been modernized and progress is being made in building replacements.

(3) With regard to submarines the trend in most navies has been to change their role from commerce destruction to anti-sub- marine warfare, although they retain the former mission in addition. Of the 16 nuclear and 243 conventional submarines belonging to NATO maritime countries, well over 150 would be available for anti-submarine duties in the Atlantic.

## Norad

North American Air Defence Command is maintained under an agreement between the United States and Canada, which integrates the Canadian and American Air Defence Commands. The Headquarters are at Col- orado Springs. Canadian Air Defence Command cur- rently has nine squadrons of CF-100 inter- ceptors armed with air-to-air missiles. American Air Defence Command weapons consist of F-104 all-weather interceptors and Bomarc missiles. The defence of American cities depends mainly on 15 Nike-Hercules ground-to-air missile units. In 1962, Canada should receive 2 Bomarc missile units for which the sites in Quebec and Ontario, are ready, and for the opera- tion of which 500 men have been trained. These defences are supported by an ex- tended radar system. Supplementing the BMEWS station in Greenland and Alaska, there are three lines of radar stations in Canada, and the 'contiguous radar system' in the United States is supported by ships and radar aircraft in the Pacific and the Atlantic and a number of 'Texas Tower' radar stations near the Atlantic coast.

The surface and submarine forces are supported by long-range patrol aircraft such as the American Neptune, the British Shack- leton, and Canadian Argus. In all, there are about 375 maritime patrol aircraft available for anti-submarine service in the eight NATO countries bordering the Atlantic.

## (C) The Channel Command

The role of Channel Command is to exercise maritime control of the English Channel and southern North Sea, to deny it to the enemy, to protect the sea lines of communi- cation and to support operations conducted by SACLANT and SACEUR. To this end, Channel Command has at its disposal a considerable proportion of the national naval forces of Belgium, France, the Nether- lands and the United Kingdom.

'Figure 2

Copyright

'Geographia' Ltd

'Figure 3

'Geographia' Ltd.

Copyright

# NATIONAL FORCES

'Table 2

Navy

'Table 3

Army Total strength: 224,000

General Population: 53,963,000 Length of military service: 1 year General Total armed forces: 330,000 increasing to 365,000 Defence budget: $2,796,000,000

Air Force Total strength: 137,000 The Air Force is organized as follows:

'Table 4

## Army

Total strength: 200,000 Of this total 53,000 are stationed in Germany and Berlin, some 20,000 in the Mediterranean, Middle East and Africa, and 20,000 in the Far East. In terms of infantry battalions, the division is: Germany and Berlin 20; Middle East and Africa 13; Caribbean 1; Far East 4. In Malaya, these form part of a Commonwealth Brigade Group. There are 7 Gurkha battalions in the Far East, but one is shortly to be transferred to Britain.

In terms of formations, 7 brigades are committed to NATO in Germany, 1 brigade is in Ber- lin, 3 brigades are based in the Middle East and Africa. In the United Kingdom, 3 brigades, plus most of the Parachute Brigade form the strategic reserve.

The armoured formations in Ger- many are equipped with Cen- turion and Conqueror tanks, some of which have received a 105 mm. howitzer. Three regi- ments are now equipped with Honest John and one with Corporal missiles (see US). The deployment of the Thun- derbird anti-aircraft missile is to be completed soon. The Vigilant anti-tank missile may shortly become operational.

## Navy

## Total strength: 96,330 men



The operational strength of the Royal Navy comprises about 210 ships (140 operational craft and 70 auxiliaries)

3 aircraft carriers and 1 com- mando carrier (Albion is also due for completion this year)

5 cruisers

20 destroyers

33 frigates

31 submarines (including the nuclear-powered submarine Dreadnought)

1 guided-missile destroyer will be completed in 1962 and will be be equipped with Sea Slug and Sea Cat surface-to-air missiles. An improved version of Sea Slug is now being developed. The new anti-submarine heli- copter Wessex is now coming into service. Aircraft carriers are receiving the Scimitar fighter-bombers and the Sea Vixen which will be equipped with the US Sidewinder and British Firestreak air-to-air missile respectively. The first operational squadron of Buccaneer low-level supersonic bombers is expected to be formed in 1962.

Air Force Total strength: 158,000 men

## Bomber Command

About 180 V-bombers, including Vulcan IIs which can deliver the Skybolt stand-off bomb and are now in squadron ser- vice. Although Blue Steel is making its final trials, it is doubtful whether it will be in service in 1962.

## Fighter Command

The supersonic Lightning is now in service, armed with the Firestreak air-to-air missile. This is also carried by the Javelin all-weather fighter. The deployment of the Blood- hound is expected to be com- pleted early in 1962. An im- proved version, capable of being transported by air, is also being developed. The BMEWS station at Fyling- dale should be completed by the summer of 1962.

## Coastal Command

Main equipment is the high- endurance Shackleton which can remain airborne for 24 hours without refuelling.

## Transport Command

Main force for long-distance air- lift comprises 23 Britannias and 10 Comets. They are supple- mented by the medium-range Beverley and Hastings aircraft. 5 Argosies will be in service by the end of 1961.

## Tactical Aircraft

The Canberra, of which the later versions are capable of 580 m.p.h. at 40,000 feet, and the Hunter fighter, speed 700 m.p.h. are the basic aircraft of RAF tactical power overseas.

## UNITED STATES

General Population: 181,000,000 Military service: Selective service for two years, but over 90% of men serving in the US forces are volunteers Total armed forces: 2,606,000 Estimated defence expenditure: $48,506,000,000 Army Total strength: 967,000 The Army consists of a Strategic Army Corps of two airborne and one infantry divisions, and 11 combat divisions. The pre- sent increase to over 1,000,000 by the end of 1961 will raise the number of combat divisions to 16. The Seventh Army of 5 divisions and 3 armoured brigades, and comprising 200,000 men, is allocated to NATO and sta- tioned in Germany. This strength may be increased to 300,000 during 1962. Three divisions are stationed in the Far East.

## MISSILES

(i) Surface-to-surface short range include: Redstone: A liquid-propellant missile, range 200 miles Pershing: a solid-fuel develop- ment of Redstone, range 100- 300 miles Corporal: range 75 miles

Sergeant: to replace Corporal, range 75 miles, has a self-con- tained guidance system Honest John: unguided field artil- lery missile, range 12 miles Lacrosse: a solid propellant rocket against field fortification, range 20 miles Little John: unguided field artil- lery lightweight missile SS 10 and 11: solid propellant anti-tank missile (See France)

## (ii) Surface-to-air

Nike-Ajax:liquid-powered guided rocket, range 25 miles Nike-Hercules: solid propellant guided missile, range 80 miles Hawk: solid propellant rocket for use against low-flying planes. Range 20 miles. Pro- gress is being made with an improved version

The equipment of the American Army with the M60 tank is still proceeding. The M60 weighs 50 tons, mounts a 105 mm. gun. The 8 in. self- propelled M55 howitzer is also in use. It has a range of over 10 miles and can fire a nuclear shell. Most armoured units are still equipped with the 44-ton M48 tank.

Navy

Total strength: 635,787 The Navy consists of 819 opera- tional ships (383 warships, 232 combatants and 204 auxiliaries) at the end of 1961. These are organized into four fleets (1st, 2nd, 6th and 7th), each of which includes attack carriers, anti-submarine carriers, sur- face and sub-surface anti-sub- marine forces, cruisers, and associated logistic and amphi- bious forces. The attack carriers Constellation and Kitty Hawk have been commissioned and the Navy has received the nuclear-pow- ered attack carrier Enterprise

and the nuclear-powered cruiser Long Beach. Seventeen new destroyers and frigates armed with guided missiles have joined the fleet in recent years and 28 more are under construction.

The Navy has 21 nuclear-pow- ered submarines in service, six of which are fleet ballistic missile submarines.

In August 1961, the Navy an- nounced that it would operate one additional attack carrier and air group. 22 amphibious ships and 11 fleet support ships are also to be reactivated. The Navy will operate one addi- tional support carrier and air group for anti-submarine war- fare purposes and purchase additional air and surface launched guided missiles. One attack transport, one destroyer and five destroyer escorts due for withdrawal from active service will be retained.

## AIRCRAFT

## (i) Fighters

F4H Phantom II: Carrier-based, all-weather fighter carrying a crew of two. Armed with air- to-air guided missiles, capable of speeds in excess of Mach 2: now being introduced.

F8U Crusader: All-weather, su- personic carrier-based fighter: armed with air-to-air rockets and conventional weapons; maximum range of 1,400 miles

F4D Skyray: Delta-wing, carrier- based, interception fighter: maximum speed exceeds 755 m.p.h.: a range of approxi- mately 900 miles.

F3H Demon Carrier-based fighter designed for day or night missions: range approxi- mately 1,500 miles, speed super- sonic.

(ii) Attack

A3J Vigilante: An all-weather attack twin-jet supersonic air- craft which can be carrier and land-based: can use conven- tional or nuclear weapons against sea and land targets in any weather: maximum speed about Mach 2; will enter fleet service in 1962.

A2F Intruder: A twin turbo-jet- powered low level naval attack bomber. It is designed to per- form close ground support missions for tactical forces or fly long distances to deliver nuclear bombs.

A3D Skywarrior: Twin-jet, car- rier-based, heavy attack plane, which can carry nuclear weap- ons, on high altitude or low naval strike missions: maxi- mum speed over 630 m.p.h.

A4D Skyhawk: Lightweight at- tack bomber: maximum speed about 700 m.p.h.; armament includes nuclear bombs, air-to- surface rockets, air-to-air mis- siles, ground attack gun pods, torpedoes, etc.; maximum range 1,150 miles.

## (iii) Anti-submarine

The three principal aircraft used by the US Navy in anti-sub- marine warfare are: the P2VF Neptune for land-based, long- range patrol; the S2F Tracker for carrier-based missions, and the HSS1 helicopter for carrier- based missions. In addition, production has begun on the HSS2 amphibian helicopter, which is powered by two gas turbine engines, and is sched- uled for fleet introduction in 1962.

MISSILES

(i) Surface-to-surface Polaris: see strategic forces Regulus I: jet-powered winged missile for ship-based launch- ings, range 500 miles



Regulus II: winged missile cap- able of Mach 2 speeds and a range of more than 1,000 miles. Some submarines are equipped with this missile

## (ii) Surface-to-air

Terrier I and II: ship-based solid propelled AA robot, range 10- 20 miles

Tartar: lighter and smaller im- proved version of Terrier, range over 10 miles

Talos: long-range ship-based AA ram-jet missile, range 65 miles

(iii) Sub-surface

Asroc: surface to underwater solid propellant rocket

(iv) Air-to-air

Sidewinder: solid rocket with infra-red guidance, range 6 miles, speed 1,800 m.p.h.

Sparrow III: range 5-8 miles, speed over 1,500 m.p.h.

## (v) Air-to-surface

Bullpup: a solid fuel radio-con- trolled missile which carries a conventional warhead and has a range of 15,000 feet

Air Force Total strength: 824,900. This may be increased to 888,000 by the summer of 1962 There are 91 wings, of which 88 are combat wings consisting of 37 strategic wings, 19 air de- fence wings and 32 tactical wings. (There are 45 aircraft in a bomber wing and 75 in a fighter wing.) The creation of two more tactical fighting wings has been decided.

## Strategic Air Command



by a fleet of KC 135 strata- tankers capable of a speed of 550 m.p.h. and slower KC 97s. The B.58 is capable of flying at Mach 2.

The tactical bombers and fighters available to Tactical Air Com- mand and North American Air Defence Command include:

F.100 Super Sabre interceptor fighter. Speed of 1,000 m.p.h. Range 1,800 miles without aerial refuelling.

F.101 Voodoo long-range fighter. Cruising speed 1,200 m.p.h. Range 1,000 miles.

F.102 Dagger. Supersonic all- weather interceptor (principally for North American Air De- fence).

F.104 Starfighter. Has reached speeds of 1,400 m.p.h. and height of 91,000 feet.

F.105 Thunderbird. Single-seater fighter-bomber. A more power- ful version is now being pro- duced, able to refuel in flight and carry heavier payloads of non-nuclear warheads, e.g. the Bullpup or Sidewinder missiles.

F.106 Dart. All-weather intercep- tor, with speed of over 1,500 m.p.h.

(see strategic forces, page 8) The B.47 has a range of 3,250 miles. The B.52, which can carry the Hound Dog air-to- surface missile in addition to free-falling bombs, has a range of 6,000 miles, with a speed of over 650 m.p.h. Both can ex- tend their range by in-flight refuelling, which is provided

Transport: 129 new long-range airlift aircraft are to be pro- cured by the middle of 1962. The Military Air Transport Ser- vice at present comprises about 480 4-engined piston aircraft designed for cargo and troops.

MISSILES

## (i) Surface-to-surface

Atlas: liquid-fuelled ICBM, range 6,000 miles. Speed 15-20,000 m.p.h. Titan: liquid-fuelled ICBM, cap- able of carrying a heavier nuclear warhead than Atlas. Range 6,000 miles. Jupiter: liquid-fuelled IRBM, range 1,500 miles.

Thor: liquid-fuelled IRBM, range 1,500 miles. Matador : jet-powered winged missile, range 300-500 miles. Mace: improved version of Mata- dor. Range 350 miles, speed supersonic, nuclear warhead.



## (ii) Air-to-ground

Hound Dog: for use on B.52s. Range 350 miles, speed super- sonic, nuclear warhead. Bullpup: see under Navy.

(iii) Surface-to-air Bomarc: long-range ram-jet mis- sile interceptor, range 400 miles, speed 1,600-2,000 m.p.h.

(iv) Air-to-air Genie: missile with a nuclear warhead carried by fighter- interceptors, range 2-4 miles, speed Mach 3.

Falcon: with nuclear or non- nuclear warhead, range 5 miles, speed supersonic.

Marine Corps

Total strength: 177,000. This will be increased to 190,000 in the first half of 1962. Organized in three divisions, each with their own air wing and amphibious support

## CENTRAL TREATY ORGANIZATION

The members of CENTO are Pakistan, Iran, Turkey, and the United Kingdom, with the United States as an associate member. The scope of the Treaty involves co-operation over a wider field than defensive preparation. CENTO does not have an international command structure as NATO does, nor are national forces allocated to it at present. Co-ordination is exercised by a Council of

military deputies including an American representative in Ankara. The main emphasis so far has been on the development of com- munications and air field to give flexibility to the forces available in the area. Strategic deterrent forces could be rapidly deployed in the area by the US 6th Fleet, from SAC bases in Turkey, and from British bases in Cyprus.

## NATIONAL FORCES

'Table 5

Thor: liquid-fuelled IRBM, range 1,500 miles. Matador jet-powered winged missile, range 300-500 miles. Mace: improved version of Mata- dor. Range 350 miles, speed supersonic, nuclear warhead.



## (ii) Air-to-ground

Hound Dog: for use on B.52s. Range 350 miles, speed super- sonic, nuclear warhead. Bullpup: see under Navy.

Bomarc: long-range ram-jet mis- sile interceptor, range 400 miles, speed 1,600-2,000 m.p.h.

## (iii) Surface-to-air

(iv) Air-to-air Genie: missile with a nuclear warhead carried by fighter- interceptors, range 2-4 miles, speed Mach 3.

Falcon: with nuclear or non- nuclear warhead, range 5 miles, speed supersonic.

Marine Corps

Total strength: 177,000. This will be increased to 190,000 in the first half of 1962. Organized in three divisions, each with their own air wing and amphibious support

## CENTRAL TREATY ORGANIZATION

The members of CENTO are Pakistan, Iran, Turkey, and the United Kingdom, with the United States as an associate member. The scope of the Treaty involves co-operation over a wider field than defensive preparation. CENTO does not have an international command structure as NATO does, nor are national forces allocated to it at present. Co-ordination is exercised by a Council of

military deputies including an American representative in Ankara. The main emphasis so far has been on the development of com- munications and air field to give flexibility to the forces available in the area. Strategic deterrent forces could be rapidly deployed in the area by the US 6th Fleet, from SAC bases in Turkey, and from British bases in Cyprus.

## NATIONAL FORCES

'Table 1

# SOUTH-EAST ASIA TREATY ORGANIZATION

The members of SEATO are Australia, France, New Zealand, Pakistan, the Philip- pine Republic, Thailand, the United King- dom and the United States. SEATO does not yet have a centralized command struc- ture and forces remain under national con- trol. SEATO co-operation is concerned not only with military defence against aggression, but also with the problem of subversion.

The main strategic forces are provided by the US Seventh Fleet (see strategic forces,

p. 9) based on Manila, units of Strategic Air Command based on Okinawa and Guam and the British Far Eastern Fleet based on Singapore.. The Commonwealth Strategic Reserve in Malaya includes British, Austra- lian and New Zealand battalions and sup- porting units, and Australian and New Zealand naval and tactical air units, but the Malay Federation has recently made it clear that bases in Malaya would not be available for SEATO operations.

## NATIONAL FORCES

'Table 1

TABLE I MOBILIZED MANPOWER

'Table 1

* Maximum

Estimated

TABLE II

# SOME COMPARATIVE ESTIMATES OF STRATEGIC STRENGTH EARLY 1962

'Table 2

'Figure 2

Includes ships in reserve

Note on maps (12 and 13).

The term 'deployed manpower' is used to comprise all forces stationed in the countries or areas illustrated irrespective of national origin, including e.g. U.S. forces in German Federal Republic and Soviet forces in East Germany. The figure of 2,000,000 for Western Europe includes French forces in Algeria.

Erratum. The figures of deployed manpower for Pakistan on the map on page 13 should read 183,000

TABLE II

# SOME COMPARATIVE ESTIMATES OF STRATEGIC STRENGTH EARLY 1962

'Table 1

'Figure 2

Includes ships in reserve

Note on maps (12 and 13).

The term 'deployed manpower' is used to comprise all forces stationed in the countries or areas illustrated irrespective of national origin, including e.g. U.S. forces in German Federal Republic and Soviet forces in East Germany. The figure of 2,000,000 for Western Europe includes French forces in Algeria.

Erratum. The figures of deployed manpower for Pakistan on the map on page 13 should read 183,000
